//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Movement
        {
            get
            {
                return SteamVR_Actions.default_Movement;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Look
        {
            get
            {
                return SteamVR_Actions.default_Look;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerPress
        {
            get
            {
                return SteamVR_Actions.default_TriggerPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerTouch
        {
            get
            {
                return SteamVR_Actions.default_TriggerTouch;
            }
        }
        
        public virtual SteamVR_Action_Single TriggerMove
        {
            get
            {
                return SteamVR_Actions.default_TriggerMove;
            }
        }
        
        public virtual SteamVR_Action_Boolean GripTouch
        {
            get
            {
                return SteamVR_Actions.default_GripTouch;
            }
        }
        
        public virtual SteamVR_Action_Single GripMove
        {
            get
            {
                return SteamVR_Actions.default_GripMove;
            }
        }
        
        public virtual SteamVR_Action_Boolean ThumbTouch
        {
            get
            {
                return SteamVR_Actions.default_ThumbTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean Jump
        {
            get
            {
                return SteamVR_Actions.default_Jump;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
